In [3]:
!pip install numpy

In [4]:
>>> import numpy as np

In [5]:
a = [1, 2, 3]
type (a)

list

In [7]:
b = np.array ([1, "a", 3])
type (b)

numpy.ndarray

In [8]:
print (a)
print (b)

[1, 2, 3]
['1' 'a' '3']


In [10]:
a = np.array ([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a.shape

(2, 3)

In [17]:
axis=1

In [18]:
a = np.array ([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
'1' + '1'

'11'

In [19]:
np.zeros ((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones ((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.empty ((5,5))

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.33512512e-306, 7.56587585e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        1.60220393e-306, 1.29060735e-306],
       [1.11261570e-306, 7.56602523e-307, 9.34609790e-307,
        8.34451504e-308, 1.33508761e-307],
       [1.33511562e-306, 8.90103560e-307, 1.42410974e-306,
        2.22507386e-306, 2.46155235e-312]])

In [25]:
np.arange(0,10,1)#(start, stop, step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.append
np.delete
np.sort

<function numpy.sort(a, axis=-1, kind=None, order=None)>

In [27]:
a = np.array ([1,2,3])
np.append (a,10)

array([ 1,  2,  3, 10])

In [28]:
a

array([1, 2, 3])

In [33]:
a = np.array ([1,2,3])
print(a)
a = np.append(a,10)
print(a)

[1 2 3]
[ 1  2  3 10]


In [36]:
a = np.delete (a, 1)
print(a)

[ 1  3 10]


In [37]:
a = np.append (a,2)
print (a)

[ 1  3 10  2]


In [38]:
a.ndim

1

In [40]:
b = np.array ([[1,2],[3,4]])
b.ndim

2

In [41]:
print (a.size)
print (b.size)

4
4


In [42]:
print (a.shape)
print (b.shape)

(4,)
(2, 2)


In [45]:
np.array ([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [49]:
a = np.arange (6)
print (a)
print(a.shape)
print()
b = a.reshape (3,2)
print (b)

[0 1 2 3 4 5]
(6,)

[[0 1]
 [2 3]
 [4 5]]


In [53]:
type (a)

numpy.ndarray

In [54]:
a = np.array ([1,2,3,4,5])
print (a.shape)
a2 = a[np.newaxis]
print (a2.shape)
print (a2)
a3 = a2 [np.newaxis]
print (a3.shape)
print (a3)


(5,)
(1, 5)
[[1 2 3 4 5]]
(1, 1, 5)
[[[1 2 3 4 5]]]


In [56]:
a= np.arange (0, 10,1)
print (a)
print(a[0])
print (a[5])
print (a[0:3])
print (a[8:])
print (a[-5:])


[0 1 2 3 4 5 6 7 8 9]
0
5
[0 1 2]
[8 9]
[5 6 7 8 9]


In [57]:
a= np.arange (0, 20,1)
print (a)
print(a[0])
print (a[5])
print (a[0:3])
print (a[8:])
print (a[-5:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
0
5
[0 1 2]
[ 8  9 10 11 12 13 14 15 16 17 18 19]
[15 16 17 18 19]


In [59]:
a = np.array ([[1,2,3],
             [4,5,6],
             [7,8,9]])
print (a)
print ()
print (a[a > 5])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[6 7 8 9]


In [62]:
lima_keatas = (a > 5)
print (a[lima_keatas])

[6 7 8 9]


In [68]:
lima_keatas = (a > 5)
lapan_kebawah = (a <8)
print (a[lima_keatas & lapan_kebawah])

[6 7]


In [82]:
lima_keatas = (a > 5)
dua = (a == 2)
print (a[lima_keatas | dua])

[2 6 7 8 9]


In [85]:
a = np.array ([[1,1],[2,2]])
b = np.array ([[2,2],[4,4]])
np.vstack ((a,b))

array([[1, 1],
       [2, 2],
       [2, 2],
       [4, 4]])

In [95]:
a = np.arange (0, 20, 1)
b = np.arange (0, 5,1)
print (a)
print (len(a))
np.hsplit (a,2)
np.hsplit (a,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
20


[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15]),
 array([16, 17, 18, 19])]

In [96]:
c = np.hsplit (a,5)
print (c)
print (c[0].size)
print (c[1].size)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15]), array([16, 17, 18, 19])]
4
4


In [97]:
a = a[0]
print ('A')
print (a)
print ()

print ('B')
print  (b)
print ()

print ('C')
print (c)
print ()

A
0

B
[0 1 2 3 4]

C
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15]), array([16, 17, 18, 19])]



In [100]:
a = np.arange (1, 5,1)
print (a)
print ()
print (a.sum())

[1 2 3 4]

10


In [101]:
data = np.array ([1,2,3])
tambah = np.array ([2,2,2])
data + tambah

array([3, 4, 5])

In [103]:
data = np.array ([[1,2,3],[4,5,6]])
tambah = np.array ([[2,2,2],[1,1,1]])
data + tambah

array([[3, 4, 5],
       [5, 6, 7]])

In [104]:
data * tambah

array([[2, 4, 6],
       [4, 5, 6]])

In [105]:
print (data)
print (data.sum())

[[1 2 3]
 [4 5 6]]
21


In [107]:
print (data)
print ()
print (data.sum())
print (data.sum(axis =0))
print ()
print (data.sum(axis=1))

[[1 2 3]
 [4 5 6]]

21
[5 7 9]

[ 6 15]


In [108]:
data.min (axis=1)

array([1, 4])

In [112]:
data = data.T
print (data)
print ()
print (data*2)
print ()


[[1 2 3]
 [4 5 6]]

[[ 2  4  6]
 [ 8 10 12]]



In [114]:
data = np.array ([[1,2], [3,4]])
print ('Data\n', data)
ones = np.ones ([2,2])
print ('Ones\n', ones)
print (data+ones)

Data
 [[1 2]
 [3 4]]
Ones
 [[1. 1.]
 [1. 1.]]
[[2. 3.]
 [4. 5.]]


In [115]:
print ('Data\n', data)
ones_row = np.ones ([1,2])
print ('Ones_row\n', ones_row)
print ('\n,', data +ones_row)

Data
 [[1 2]
 [3 4]]
Ones_row
 [[1. 1.]]

, [[2. 3.]
 [4. 5.]]


In [123]:
a_1 = np.array ([[1,2,3],[4,5,6]])
print (a_1)
print ()
a_2 = np.array ([[7,8],[9,10],[10,11]])
print (a_2)
print ('size=', a_2.size)
print ('shape=', a_2.shape)
print ()
print ('Result')
print (np.dot (a_1, a_2))
print ()
                        
print ('Result2')
print (a_1 , a_2)

[[1 2 3]
 [4 5 6]]

[[ 7  8]
 [ 9 10]
 [10 11]]
size= 6
shape= (3, 2)

Result
[[ 55  61]
 [133 148]]

Result2
[[1 2 3]
 [4 5 6]] [[ 7  8]
 [ 9 10]
 [10 11]]


In [124]:
data = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print (data)
print (data[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8


In [129]:
data = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print (data)
print (data[0,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [132]:
data = np.array ([[1,2],[2,3],[3,4],[4,5],[5,6],[6,7],[7,8],[8,9]])
display (data)
print (data)
print (data.ndim)
print (data.shape)
print (data[0,1])#jumlah harus sama dengan list array

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6],
       [6, 7],
       [7, 8],
       [8, 9]])

[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]
 [6 7]
 [7 8]
 [8 9]]
2
(8, 2)
2


In [133]:
print (data)
print (data.T)

[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]
 [6 7]
 [7 8]
 [8 9]]
[[1 2 3 4 5 6 7 8]
 [2 3 4 5 6 7 8 9]]


In [136]:
data = np.array ([[1,2,3],[2,3,4],[3,4,5],[4,5,6],[5,6,7],[6,7,8],[7,8,9],[8,9,9]])
display (data)
print (data)
print (data.ndim)
print (data.shape)
print (data[2,1])#jumlah harus sama dengan list array

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9],
       [8, 9, 9]])

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]
 [8 9 9]]
2
(8, 3)
4


In [140]:
data = np.ones ((3,2,2,4))
print (data)
print (np.ones((3,2,2,4)).ndim)
print (np.ones((3,2,2,4)).shape)
print (data[0])

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]
4
(3, 2, 2, 4)
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [159]:
data = np.random.random((3,2,2,3))
print (data)
print ()
print ('flattened')
print (data.flatten())

[[[[0.52039777 0.47029129 0.49333023]
   [0.74298203 0.84401628 0.3299695 ]]

  [[0.64047501 0.9884695  0.87995982]
   [0.73377212 0.74617854 0.31540199]]]


 [[[0.27353219 0.28877918 0.97672277]
   [0.07707686 0.90314241 0.98252817]]

  [[0.93432832 0.10298905 0.23543065]
   [0.65236985 0.04842055 0.28694194]]]


 [[[0.16021199 0.32971312 0.47077192]
   [0.11313341 0.6236446  0.56457146]]

  [[0.09434341 0.85313978 0.43618983]
   [0.95829084 0.1263925  0.14583539]]]]

flattened
[0.52039777 0.47029129 0.49333023 0.74298203 0.84401628 0.3299695
 0.64047501 0.9884695  0.87995982 0.73377212 0.74617854 0.31540199
 0.27353219 0.28877918 0.97672277 0.07707686 0.90314241 0.98252817
 0.93432832 0.10298905 0.23543065 0.65236985 0.04842055 0.28694194
 0.16021199 0.32971312 0.47077192 0.11313341 0.6236446  0.56457146
 0.09434341 0.85313978 0.43618983 0.95829084 0.1263925  0.14583539]


In [137]:
print (data)
print (data.T)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]
 [8 9 9]]
[[1 2 3 4 5 6 7 8]
 [2 3 4 5 6 7 8 9]
 [3 4 5 6 7 8 9 9]]


In [160]:
data = np.array ([[1,2,3],[0,10,100]])
print (data)
print ('shape =', data.shape)
print ()
print (data.reshape (3,2))
print ('shape = ', data.reshape)


[[  1   2   3]
 [  0  10 100]]
shape = (2, 3)

[[  1   2]
 [  3   0]
 [ 10 100]]
shape =  <built-in method reshape of numpy.ndarray object at 0x0000022289AA7750>


In [162]:
print (5**2)
print (np.square (5))

25
25


In [169]:
#1/n sigma i-n (Yi - Yi >)**
n =1
yi=2
1/n * np.sum (np.square (yi -yi >1))

0.0